App\Entity\Calendar:
    type: entity
    repositoryClass: App\Repository\CalendarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        events:
            targetEntity: App\Entity\Event
            mappedBy: calendar